
name : auto_pr_to_master

on :
  push :
    branches : [ beta ]

jobs :

  forward :
    uses : Wandalen/game_chess/.github/workflows/AutoPr.yml@master
    with :
      src_branch : 'beta'
      dst_branch : 'master'
    secrets :
      PRIVATE_GITHUB_TOKEN : '${{ secrets.PRIVATE_GITHUB_TOKEN }}'


