
name : auto_pr_to_beta

on :
  push :
    branches : [ alpha ]

jobs :

  forward :
    uses : Wandalen/game_chess/.github/workflows/AutoPr.yml@master
    with :
      src_branch : 'alpha'
      dst_branch : 'beta'
    secrets :
      PRIVATE_GITHUB_TOKEN : '${{ secrets.PRIVATE_GITHUB_TOKEN }}'
