
name: beta

on :
  pull_request_target :
    branches:
      - master

concurrency :

  group : beta_pull_request
  cancel-in-progress : true

env:
  CARGO_TERM_COLOR: always

jobs:

  desktop:
    uses: Wandalen/game_chess/.github/workflows/DesktopCommon.yml@master
    with:
      artifacts: 'false'
      build: 'fast'
      toolchain: 'stable'
  web:
    uses: Wandalen/game_chess/.github/workflows/WebCommon.yml@master
    with:
      artifacts: 'false'
      build: 'fast'
      toolchain: 'stable'
