
name: DesktopPush

on :
  push :
    branches : [ alpha ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    # if: "contains( github.event.head_commit.message, '[build]' )"
    uses: Wandalen/game_chess/.github/workflows/DesktopCommon.yml@master
    with:
      artifacts: 'false'
      build: 'fast'
      toolchain: 'stable'

